---
- hosts: localhost
  become: true
  ignore_errors: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - chezmoi
        - firefox
        - thunderbird
        - zoxide
        - espanso
        - keepassxc
        - obsidian


  tasks:
    # Uncomment these lines if you have node and zsh tasks
    # - name: Node tasks
    #   include_tasks: tasks/node.yml
    #   tags:
    #     - node

    # - name: ZSH tasks
    #   include_tasks: tasks/zsh.yml
    #   tags:
    #     - zsh
#
    # - name: Install Oh-my-posh tasks
    #   include_tasks: tasks/oh-my-posh.yml
    #   tags:
    #    - zsh
    # - name: Install chezmoi tasks
    #   include_tasks: tasks/chezmoi.yml
    #   tags:
    #    - chezmoi
#
   # - name: Install Firefox tasks
   #   include_tasks: tasks/firefox.yml
   #   tags:
   #     - firefox

    #- name: Install Thunderbird tasks
    #  include_tasks: tasks/thunderbird.yml
    #  tags:
    #    - thunderbird

    #- name: Install Zoxide tasks
    #  include_tasks: tasks/zoxide.yml
    #  tags:
    #    - zoxide
    - name: Install Espanso tasks
      include_tasks: tasks/espanso.yml
      tags:
        - espanso
    - name: Install Keepassxc tasks
      include_tasks: tasks/keepassxc.yml
      tags:
        - keepassxc.yml
    - name: Install Obsidian tasks
      include_tasks: tasks/obsidian.yml
      tags:
        - obsidian
