---
- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - chezmoi
        - firefox
  tasks:
   - name: Node tasks
     include_tasks: tasks/node.yml
     tags:
       - node
   - name: ZSH tasks
     include_tasks: tasks/zsh.yml
     tags:
       - zsh
   - name: chezmoi
     include_tasks: tasks/chezmoi.yml
     tags:
        - chezmoi
   - name: firefox
     include_tasks: tasks/firefox.yml
     tags:
        - firefox